---
# Service for exposing Swap
apiVersion: v1
kind: Service
metadata:
  name: swap-service
  labels:
    app: swap
spec:
  type: NodePort # Makes the service accessible on a static port on each Node in the cluster.
  selector:
    app: swap
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - targetPort: 8000 # port that containers are listening on
      port: 8000 # port exposed internally in the cluster
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007 # a static port assigned on each the node
