#+title: Notas

* Aula 07-03-2023 :: Tarefas
** Conhecer os utilizadores
~Nunca devemos ser nós o utilizador~
~Nunca nós prórpios como modelo~

** Classes de utilização
- utilizadores diretos :: interagem diretamente no sistema
- utilizadores indiretos :: interagem indiretamente

  EX: quando vamos a uma biblioteca requisitar um livro e a senhora anota o nosso pedido, os alunos sao os utilizadores indiretos

- utilizadores remotos :: interessados no funcionamento do sistema

  EX: administradores do sistema ou assim

- utilizadores de suporte

- ou ainda ::
  + se sao obrigados a utilizar o sistema ou nao

    tipo nós somos obrigados a usar a blackboar

  + intermitentes ou continuados


Tanto os utilizaddores indiretos como remotos não costumam aparecer nos diagramas
** Niveis de pericia
"Analogia"
- utilizadores inexperientes ::  tem medo de estragar
- Executantes competentes ::  já nao tem tanto medo, experimentam e estragam o seu proprio sistema
- peritos :: estragam o sistema dos outros

* Aula 14-03-2023 :: Prototipagem
** Estilos de interaçao
é fundamental estabelecer o tipo de interface mais adequado

*** Linha de commandos
Utilizado mais por utilizadores experientes, visto ser mais rapido e pratico do que usar o rato.

*** Menu-driven
Melhores para ~utilizadores inexperientes~

Precisamos de ter mais atencao como estao dispostas as opcoes (havendo uma hierarquia)

** Prototipagem
*** Podem ser de ~baixa~ ou de ~alta~.

Exemplo de casa ou "renovacao?":

- Baixa fidelidade :: construcao 3d
- Alta fidelidade :: construcao real

*** Throw-away vs evolucionários

- throw-away :: depois da prototipagem e de aceite, passamos para a construcao e podemos deitar a prototipagem "ao lixo" (usar e deitar fora)

- evolucionário :: na prototipagem desenvolvemos um sistema, e podemos usar isso para desenvolver a construção final

** Protótipos de baixa fidelidade

Protótipos horizontais (~só camada de IU~)

Desenhos/capturas de écran

Pode ser feito em papel ou com apoio de ferramentas.
** Protótipos em papel
De baixo custo e temos uma maior liberdade (principalmente em termos de abstração)
** Mapas de navegação

Conseguimos uma representação mais detalhada do nosso produto final
* Aula 21-03-2023 :: Desenhar para a usabilidade
** Principios de usabilidade
- deve ser fácil de aprender
- robusto :: permitir ao utilizador que tá a fazer as coisas (resistente ao erro)
** 8 golden rules
1. Consistencia
2. permitir aos utilizadores frequentes utilizar atalhos
3. fornecer feedback informativo
4. mostrar dialogo ao utilizador (validacao..)
5. oferecer prevenção de erros e tratamento dos mesmos
6. permitir desfazer as ações
7. suportar locus internos de controlo
   devemos desenhar a interface de modo a que utilizador pense que está no controlo
8. reduzir a memória de curto prazo do utilizador
** heurísticas de nielse
1. visibilidade do estado do sistema
2. correspondência entre o sistema e o mundo real
   "utilizar metáforas"
3. controlo e liberdade do utilizador
4. consistência e normas
5. prevenção de erros
6. reconhecer em vez de recordar
7. flexibilidade e eficiência de utilização
8. desenho estético e minimalista
9. ajudar os utilizadores a reconhecer, diganosticar e recuperar de erros
10. ajuda e documentação
* Aula 28-03-2023 :: Design patterns

- Breadcrumb Navigation :: Este padrão permite que os utilizadores voltem atrás em seus passos mostrando o caminho que eles percorreram para chegar à sua localização atual. É especialmente útil para aplicações com muito conteúdo.

- Progressive Disclosure :: Este padrão é usado para simplificar a interface do usuário ocultando recursos avançados ou raramente usados até que sejam necessários.

- Cards :: Este padrão é usado para exibir pequenos pedaços de informação de maneira visualmente atraente. Cada cartão contém uma pequena quantidade de informações e pode ser facilmente lido pelo utilizador.

- feedback loop :: Use when you want to enable users to react immediately on feedback from previous actions.

- inline hints :: fornecer ao utilizador informacoes sobre novas ou unfamiliar features na interface

- Home link :: conseguir voltar ao ponto de start do site através

- adaptable view ::  o utilizador consegue alterar o tamanho da fonte da letra

* Aula 11-04-2023 :: Avaliacao
** Avaliação de usabilidade
- inspeccao por peritos :: identificar potenciais problemas
- testes automatizados
- métodos empíricos :: medir a realidade


** metodos analiticos
- a analise é realizada sem recorrer a utilizadores reais :: recorre se a prototipos/modelos do sistema

  custo é mais baixo do que os ~metodos empiricos~

- O principal objectivo é prever potenciais problemas de usabilidade (o que é diferente de avaliar a usabilidade).

** avaliacao heuristica
- Um conjunto de heurísticas é utilizado para guiar a análise.
- Heurística :: Metodologia que conduz à sabedoria científica ou à
resolução de problemas.
* Aula 16-05-2023 :: Conclusão

** teste

- 2 folhas manuscritas
